Decided on first test, than quality - different steps for clarification)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -121,13 +121,66 @@ jobs:
         egrep -i "sqlalchemy|zeroconf|pyserial" requirements_test_all.txt > ~/tmp/requirements_test_extra.txt
         pip install -r ~/tmp/requirements_test_extra.txt
         pip install $(grep require ~/work/plugwise-beta/plugwise-beta/custom_components/plugwise/manifest.json | cut -f 4 -d '"')
-    # Remove this pytest eventually so we first flake/lint like pre-commit behaves
-    - name: pytest-temp-before-flake
+    - name: pytest
       run: |
         cd ~/ha-core
         . venv/bin/activate
         pytest --cov=homeassistant/components/plugwise/ --cov-report term-missing -- tests/components/plugwise/
 
+  # Reset GIT, preload and validate code
+  ha-core-quality:
+    runs-on: ubuntu-latest
+    name: Verify code quality
+    needs: ha-core-test
+    steps:
+    - name: Check out committed code
+      uses: actions/checkout@v2
+    - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+      id: python
+      uses: actions/setup-python@v2
+      with:
+        python-version: ${{ env.DEFAULT_PYTHON }}
+    - name: Restore base HA-core Python ${{ env.DEFAULT_PYTHON }} virtual environment
+      id: cache-hacore
+      uses: actions/cache@v2
+      env:
+        cache-name: cache-hacore
+      with:
+        path: ~/ha-core
+        key: >-
+          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-hacore-${{
+          steps.python.outputs.python-version }}-${{
+          hashFiles('custom_components/plugwise/manifest.json') }}-${{
+          hashFiles('~/ha-core/.git/plugwise-tracking') }}
+        restore-keys: |
+          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-hacore-${{ steps.python.outputs.python-version }}-
+          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-hacore
+          ${{ env.CACHE_VERSION}}-${{ runner.os }}
+          ${{ env.CACHE_VERSION}}
+    - name: Fail job if Python cache restore failed
+      if: steps.cache-hacore.outputs.cache-hit != 'true'
+      run: |
+        echo "Failed to restore Python ${{ env.DEFAULT_PYTHON }} virtual environment from cache"
+        exit 1
+    - name: Remove current code and tests
+      run: |
+        cd ~/ha-core
+        echo "Last commit message:"
+        git log -1 --pretty=%B
+        rm -r homeassistant/components/plugwise tests/fixtures/plugwise tests/components/plugwise
+    - name: Copy code and tests
+      run: |
+        cp -r custom_components/plugwise ~/ha-core/homeassistant/components/
+        cp -r tests/fixtures/plugwise ~/ha-core/tests/fixtures/
+        cp -r tests/components/plugwise ~/ha-core/tests/components/
+    - name: Prepare requirements (be)for(e) plugwise
+      run: |
+        cd ~/ha-core
+        . venv/bin/activate
+        mkdir ~/tmp
+        egrep -i "sqlalchemy|zeroconf|pyserial" requirements_test_all.txt > ~/tmp/requirements_test_extra.txt
+        pip install -r ~/tmp/requirements_test_extra.txt
+        pip install $(grep require ~/work/plugwise-beta/plugwise-beta/custom_components/plugwise/manifest.json | cut -f 4 -d '"')
     - name: flake8
       run: |
         cd ~/ha-core
@@ -141,11 +194,5 @@ jobs:
         . venv/bin/activate
         pip install pylint
         pylint homeassistant/components/plugwise/*py
-        # disable for further figuring out
+        # disable for further figuring out, apparently HA doesn't pylint against test
         #pylint tests/components/plugwise/*py
-    - name: pytest
-      run: |
-        cd ~/ha-core
-        . venv/bin/activate
-        pytest --cov=homeassistant/components/plugwise/ --cov-report term-missing -- tests/components/plugwise/
-
