Quickpass re-normal - dev fail improve more

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -140,14 +140,21 @@ jobs:
         id: ha_core_release_tests
         continue-on-error: ${{ needs.determine-mode.outputs.strict_dev == 'true' }} # Allow master failures only if dev is strict
         run: |
-          #if GITHUB_ACTIONS="" scripts/core-testing.sh; then
-          if exit 1; then
-            echo "Successfully tested against released HA-core"
-            echo "failed=false" >> "$GITHUB_OUTPUT"
-          else
+          set +e
+
+          #GITHUB_ACTIONS="" scripts/core-testing.sh
+          exit 1
+          EXIT_CODE=$?
+
+          if [ $EXIT_CODE -ne 0 ]; then
             echo "::warning::Release HA core incompatibility"
             echo "failed=true" >> "$GITHUB_OUTPUT"
+          else
+            echo "Successfully tested against released HA-core"
+            echo "failed=false" >> "$GITHUB_OUTPUT"
           fi
+
+          exit $EXIT_CODE
 
   ha-core-dev:
     runs-on: ubuntu-latest
@@ -188,14 +195,21 @@ jobs:
         id: ha_core_dev_tests
         continue-on-error: ${{ needs.determine-mode.outputs.strict_dev == 'false' }} # Allow dev failures unless strict
         run: |
-          #if GITHUB_ACTIONS="" BRANCH="dev" scripts/core-testing.sh; then
-          if exit 1; then
-            echo "Successfully tested against dev HA-core"
-            echo "failed=false" >> "$GITHUB_OUTPUT"
-          else
+          set +e
+
+          #GITHUB_ACTIONS="" BRANCH="dev" scripts/core-testing.sh
+          exit 0
+          EXIT_CODE=$?
+
+          if [ $EXIT_CODE -ne 0 ]; then
             echo "::warning::Development HA core incompatibility"
             echo "failed=true" >> "$GITHUB_OUTPUT"
+          else
+            echo "Successfully tested against dev HA-core"
+            echo "failed=false" >> "$GITHUB_OUTPUT"
           fi
+
+          exit $EXIT_CODE
 
   final-comment:
     runs-on: ubuntu-latest
