Quickpass re-normal - release fail

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -6,7 +6,6 @@ name: Test PR against HA-core
 env:
   CACHE_VERSION: 30
   DEFAULT_PYTHON: "3.13"
-  STRICT_DEV: false
 
 # Do not run on 'push' (as the flow doesn't have access to the labels) - also disabled workflow_dispatch as such
 # Workaround could be something like
@@ -15,6 +14,16 @@ env:
 #          PR_LABELS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
 #          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels")
 #          echo "PR Labels: $PR_LABELS"
+
+# Release / dev mode
+#
+# Assuming release mode testing
+# - PR is not labeled with require-dev-pass label
+# - Release test should NOT continue-on-error (as a whole)
+#   - continue-on-error = false
+# - Actual release test should just fail and become red
+# - Dev test SHOULD continue-on-error (as a whole)
+# - Actual dev test should continue-on-error and report accordingly
 
 on:
   pull_request:
@@ -25,6 +34,14 @@ on:
       - unlabeled
 
 jobs:
+  shellcheck:
+    name: Shellcheck
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4.2.2
+      - name: Run ShellCheck
+        uses: ludeeus/action-shellcheck@master
+
   determine-mode:
     name: Determine release or dev mode
     runs-on: ubuntu-latest
@@ -40,14 +57,6 @@ jobs:
           else
             echo "strict_dev=false" >> $GITHUB_OUTPUT
           fi
-
-  shellcheck:
-    name: Shellcheck
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4.2.2
-      - name: Run ShellCheck
-        uses: ludeeus/action-shellcheck@master
 
   pre-commit:
     name: Validate pre-commit requirements
@@ -96,7 +105,7 @@ jobs:
   ha-core-release:
     runs-on: ubuntu-latest
     name: Setup for HA-core (release/master)
-    continue-on-error: ${{ needs.determine-mode.outputs.strict_dev == 'false' }}
+    continue-on-error: ${{ needs.determine-mode.outputs.strict_dev == 'true' }} # Allow master failures only if dev is strict
     needs:
       - determine-mode
       - pre-commit
@@ -105,14 +114,6 @@ jobs:
     steps:
       - name: Check out committed code
         uses: actions/checkout@v4.2.2
-      - name: Determine Branch Test Mode
-        id: determine_mode
-        run: |
-          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'require-dev-pass') }}" == "true" ]]; then
-            echo "STRICT_DEV=true" >> $GITHUB_ENV
-          else
-            echo "STRICT_DEV=false" >> $GITHUB_ENV
-          fi
       - name: Set up Python ${{ env.DEFAULT_PYTHON }}
         id: python
         uses: actions/setup-python@v5.4.0
@@ -135,31 +136,25 @@ jobs:
             ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-hacore
             ${{ env.CACHE_VERSION}}-${{ runner.os }}
             ${{ env.CACHE_VERSION}}
-      - name: Test through HA-core (master/release) - continue-on-error = ${{ env.STRICT_DEV == 'false' }}
+      - name: Test through HA-core (master/release) - continue-on-error = ${{ needs.determine-mode.outputs.strict_dev == 'true' }}
         id: ha_core_release_tests
-        continue-on-error: ${{ env.STRICT_DEV == 'true' }} # Allow master failures only if dev is strict
+        continue-on-error: ${{ needs.determine-mode.outputs.strict_dev == 'true' }} # Allow master failures only if dev is strict
         run: |
-          echo "true" > result.txt
           #GITHUB_ACTIONS="" scripts/core-testing.sh
-          exit 0
+          exit 1
           if [ $? -ne 0 ]; then
-            echo "::warning::Release  HA core incompatibility"
-            echo "true" > result.txt
+            echo "::warning::Release HA core incompatibility"
+            echo "failed=true" >> "$GITHUB_OUTPUT"
+            exit 1
           else
             echo "Successfully tested against released HA-core"
-            echo "false" > result.txt
+            echo "failed=false" >> "$GITHUB_OUTPUT"
           fi
-      - name: Set output explicitly
-        id: capture_release
-        if: always()
-        run: |
-          FAILED=$(cat result.txt)
-          echo "failed=$FAILED" >> "$GITHUB_OUTPUT"
 
   ha-core-dev:
     runs-on: ubuntu-latest
     name: Setup for HA-core (dev)
-    continue-on-error: ${{ needs.determine-mode.outputs.strict_dev == 'true' }}
+    continue-on-error: ${{ needs.determine-mode.outputs.strict_dev == 'false' }} # Allow dev failures unless strict
     needs:
       - determine-mode
       - pre-commit
@@ -168,14 +163,6 @@ jobs:
     steps:
       - name: Check out committed code
         uses: actions/checkout@v4.2.2
-      - name: Determine Branch Test Mode
-        id: determine_mode
-        run: |
-          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'require-dev-pass') }}" == "true" ]]; then
-            echo "STRICT_DEV=true" >> $GITHUB_ENV
-          else
-            echo "STRICT_DEV=false" >> $GITHUB_ENV
-          fi
       - name: Set up Python ${{ env.DEFAULT_PYTHON }}
         id: python
         uses: actions/setup-python@v5.4.0
@@ -199,45 +186,32 @@ jobs:
             ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-hacore
             ${{ env.CACHE_VERSION}}-${{ runner.os }}
             ${{ env.CACHE_VERSION}}
-      - name: Test through HA-core (dev) - continue-on-error = ${{ env.STRICT_DEV == 'false' }}
+      - name: Test through HA-core (dev) - continue-on-error = ${{ needs.determine-mode.outputs.strict_dev == 'false' }}
         id: ha_core_dev_tests
-        continue-on-error: ${{ env.STRICT_DEV == 'false' }} # Allow dev failures unless strict
+        continue-on-error: ${{ needs.determine-mode.outputs.strict_dev == 'false' }} # Allow dev failures unless strict
         run: |
-          echo "true" > result.txt
           #GITHUB_ACTIONS="" BRANCH="dev" scripts/core-testing.sh
-          exit 1
+          exit 0
           if [ $? -ne 0 ]; then
             echo "::warning::Development HA core incompatibility"
-            echo "true" > result.txt
+            echo "failed=true" >> "$GITHUB_OUTPUT"
+            exit 1
           else
             echo "Successfully tested against dev HA-core"
-            echo "false" > result.txt
+            echo "failed=false" >> "$GITHUB_OUTPUT"
           fi
-      - name: Set output explicitly
-        id: capture_dev
-        if: always()
-        run: |
-          FAILED=$(cat result.txt)
-          echo "failed=$FAILED" >> "$GITHUB_OUTPUT"
 
   final-comment:
     runs-on: ubuntu-latest
     needs: [ha-core-release, ha-core-dev]
+    if: failure()
     steps:
-      - name: Determine Branch Test Mode
-        id: determine_mode
-        run: |
-          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'require-dev-pass') }}" == "true" ]]; then
-            echo "STRICT_DEV=true" >> $GITHUB_ENV
-          else
-            echo "STRICT_DEV=false" >> $GITHUB_ENV
-          fi
       - name: Create combined comment
         run: |
           # Get the results of the previous scripts
-          STRICT_DEV=$STRICT_DEV
-          DEV_TESTS_FAILED=${{ needs.ha-core-dev.outputs.dev_failed }}
-          RELEASE_TESTS_FAILED=${{ needs.ha-core-release.outputs.release_failed }}
+          STRICT_DEV=${{ needs.determine-mode.outputs.strict_dev }}
+          RELEASE_TESTS_FAILED="${{ needs.ha-core-release.outputs.failed }}"
+          DEV_TESTS_FAILED="${{ needs.ha-core-dev.outputs.failed }}"
           FAIL_COUNT=0
 
           if [[ $DEV_TESTS_FAILED == "true" ]]; then
