Quickfail normal

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -72,19 +72,19 @@ jobs:
             ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-hacore
             ${{ env.CACHE_VERSION}}-${{ runner.os }}
             ${{ env.CACHE_VERSION}}
-      - name: Set-up environment
-        run: |
-          scripts/setup.sh
-      - name: Install pre-commit dependencies
-        run: |
-          . venv/bin/activate
-          pre-commit install-hooks
-      - name: Run all-files pre-commit excluding testing
-        run: |
-          . venv/bin/activate
-          pre-commit run --all-files --show-diff-on-failure
-        env: # While not problematic, save time on performing the local hooks as they are run from the complete script in the next job
-          SKIP: local-test-core-prep,local-test-pip-prep,local-testing,local-quality
+#      - name: Set-up environment
+#        run: |
+#          scripts/setup.sh
+#      - name: Install pre-commit dependencies
+#        run: |
+#          . venv/bin/activate
+#          pre-commit install-hooks
+#      - name: Run all-files pre-commit excluding testing
+#        run: |
+#          . venv/bin/activate
+#          pre-commit run --all-files --show-diff-on-failure
+#        env: # While not problematic, save time on performing the local hooks as they are run from the complete script in the next job
+#          SKIP: local-test-core-prep,local-test-pip-prep,local-testing,local-quality
 
   # Prepare default python version environment
   ha-core-release:
@@ -134,7 +134,8 @@ jobs:
         continue-on-error: ${{ env.STRICT_DEV == 'true' }} # Allow master failures only if dev is strict
         run: |
           echo "true" > result.txt
-          GITHUB_ACTIONS="" scripts/core-testing.sh
+#          GITHUB_ACTIONS="" scripts/core-testing.sh
+          exit 1
           if [ $? -ne 0 ]; then
             echo "::warning::Release  HA core incompatibility"
             echo "true" > result.txt
@@ -197,7 +198,8 @@ jobs:
         continue-on-error: ${{ env.STRICT_DEV == 'false' }} # Allow dev failures unless strict
         run: |
           echo "true" > result.txt
-          GITHUB_ACTIONS="" BRANCH="dev" scripts/core-testing.sh
+#          GITHUB_ACTIONS="" BRANCH="dev" scripts/core-testing.sh
+          exit 0
           if [ $? -ne 0 ]; then
             echo "::warning::Development HA core incompatibility"
             echo "true" > result.txt
