Local works, lets action

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -27,44 +27,29 @@ jobs:
         uses: actions/setup-python@v3
         with:
           python-version: ${{ env.DEFAULT_PYTHON }}
-      - name: Restore base HA-core Python ${{ env.DEFAULT_PYTHON }} virtual environment
+      - name: Restore base HA-core Python ${{ env.DEFAULT_PYTHON }} environment
         id: cache-hacore
         uses: actions/cache@v2
         env:
           cache-name: cache-hacore
         with:
-          path: ~/ha-core
           key: >-
             ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-hacore-${{
             steps.python.outputs.python-version }}-${{
-            hashFiles('custom_components/plugwise/manifest.json') }}-${{
-            hashFiles('~/ha-core/.git/plugwise-tracking') }}
+            hashFiles('./custom_components/plugwise/manifest.json') }}-${{
+            hashFiles('./ha-core/.git/plugwise-tracking') }}
           restore-keys: |
             ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-hacore-${{ steps.python.outputs.python-version }}-
             ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-hacore
             ${{ env.CACHE_VERSION}}-${{ runner.os }}
             ${{ env.CACHE_VERSION}}
-      # Workaround, even though cache restored on new(er) PR
-      # cache-hit isn't registered (although cache is restored
       - name: Create HA-core Python virtual environment
         run: |
-          if [ -f ~/ha-core/requirements_test_all.txt ]; then
-              cd ~/ha-core
-              git config pull.rebase true
-              git reset --hard
-              git pull
-          else
-              git clone https://github.com/home-assistant/core.git ~/ha-core
-              cd ~/ha-core
-              git config pull.rebase true
-              git checkout dev
-              script/setup
-              . venv/bin/activate
-              pip install -q -r requirements_test.txt
-          fi
-          git log -1 | head -1 > ~/ha-core/.git/plugwise-tracking
+          scripts/core-testing.sh core_prep
+      - name: Prepare HA-core Python virtual environment
+        run: |
+          scripts/core-testing.sh pip_prep
 
-  # Reset GIT, preload and execute tests
   ha-core-test:
     runs-on: ubuntu-latest
     name: Test against HA-core
@@ -77,18 +62,17 @@ jobs:
         uses: actions/setup-python@v3
         with:
           python-version: ${{ env.DEFAULT_PYTHON }}
-      - name: Restore base HA-core Python ${{ env.DEFAULT_PYTHON }} virtual environment
+      - name: Restore base HA-core Python ${{ env.DEFAULT_PYTHON }} environment
         id: cache-hacore
         uses: actions/cache@v2
         env:
           cache-name: cache-hacore
         with:
-          path: ~/ha-core
           key: >-
             ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-hacore-${{
             steps.python.outputs.python-version }}-${{
-            hashFiles('custom_components/plugwise/manifest.json') }}-${{
-            hashFiles('~/ha-core/.git/plugwise-tracking') }}
+            hashFiles('./custom_components/plugwise/manifest.json') }}-${{
+            hashFiles('./ha-core/.git/plugwise-tracking') }}
           restore-keys: |
             ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-hacore-${{ steps.python.outputs.python-version }}-
             ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-hacore
@@ -97,26 +81,53 @@ jobs:
       - name: Fail job if Python cache restore failed
         if: steps.cache-hacore.outputs.cache-hit != 'true'
         run: |
-          echo "Failed to restore Python ${{ env.DEFAULT_PYTHON }} virtual environment from cache"
+          echo "Failed to restore Python ${{ env.DEFAULT_PYTHON }} environment from cache"
           exit 1
-      - name: Debug
+      - name: Test
         run: |
-          echo "git top level"
-          git rev-parse --show-toplevel
-          echo "pwd"
-          pwd
-          echo "env"
-          env
-          echo "set"
-          set
-          echo "ls s"
-          ls -l
-          ls -l ~
-          ls -l ~/ha-core
+          scripts/core-testing.sh testing
+
+  ha-core-quality:
+    runs-on: ubuntu-latest
+    name: Run linting/quality
+    needs: ha-core-test
+    steps:
+      - name: Check out committed code
+        uses: actions/checkout@v3
+      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+        id: python
+        uses: actions/setup-python@v3
+        with:
+          python-version: ${{ env.DEFAULT_PYTHON }}
+      - name: Restore base HA-core Python ${{ env.DEFAULT_PYTHON }} environment
+        id: cache-hacore
+        uses: actions/cache@v2
+        env:
+          cache-name: cache-hacore
+        with:
+          key: >-
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-hacore-${{
+            steps.python.outputs.python-version }}-${{
+            hashFiles('./custom_components/plugwise/manifest.json') }}-${{
+            hashFiles('./ha-core/.git/plugwise-tracking') }}
+          restore-keys: |
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-hacore-${{ steps.python.outputs.python-version }}-
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-hacore
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}
+            ${{ env.CACHE_VERSION}}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-hacore.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python ${{ env.DEFAULT_PYTHON }} environment from cache"
+          exit 1
+      - name: Test
+        run: |
+          scripts/core-testing.sh quality
 
   shellcheck:
     name: Shellcheck
     runs-on: ubuntu-latest
+    needs: ha-core-quality
     steps:
       - uses: actions/checkout@v3
       - name: Run ShellCheck
